slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Core Plugin Parameters (Required for the mapping engine to run)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_region_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function_type: NONE

    # ROS Framework Frames & Topics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping # running in online 2D mapping mode

    # Your Custom Tuned Parameters
    minimum_travel_heading: 0.04
    minimum_travel_distance: 0.10
    map_update_interval: 0.5

    # Slam Toolbox Scan Matching Tuners
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.5
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Core Dimensions
    max_laser_range: 20.0
    minimum_time_interval: 0.06
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
